config/routes.rb
Cats99::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :cats
  resources :cat_rental_requests do
    patch :approve
    patch :deny
  end
  root :to => 'cats#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :reset_session_token!
  validates :user_name, :session_token, :uniqueness => true, :presence => true

  has_many :cats, :dependent => :destroy
  has_many :session_tokens, :dependent => :destroy


  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
  end

  def password=(plaintext)
    self.password_digest = BCrypt::Password.create(plaintext)
  end

  def is_password?(plaintext)
    BCrypt::Password.new(self.password_digest).is_password?(plaintext)
  end

  def self.find_by_credentials(params)
    user = User.find_by_user_name(params[:user_name])
    if user
      return user if user.is_password?(params[:password])
    end
    nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_login, only: [:new, :create]
  before_action :require_login, only: [:show, :edit, :destroy, :update]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @cats = Cat.where(:user_id => @user.id)
    @sessions = SessionToken.where(:user_id => @user.id)
    render :show
  end

  def index
    @users = User.all
    render :index
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    if @user.save
      @user.reset_session_token!
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    logout!
    @user.destroy!
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<form action="<%=users_url%>" method="POST" accept-charset="utf-8">


  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <h1> Sign Up </h1>
  <p>
  <label_for="user_name">User Name</label>
  <input type="text" name="user[user_name]" id = "user_name" value = "<%= @user.user_name %>" required/>
  </p>

  <p>
  <label_for="password">Password</label>
  <input type="password" name="user[password]" id = "password" required/>
  </p>

  <input type="submit" value="Sign Up Now!"/>
</form>

app/views/users/show.html.erb
<h1>Cats</h1>

<ul>
  <% @cats.each do |cat| %>
    <li> <%= link_to(cat.name, cat_url(cat)) %>
  <% end %>
</ul>

<p>
  Currently logged in from:
  <ul>
    <% @sessions.each do |sesh| %>
      <li><%= "#{sesh.device} (#{sesh.login_location})"%>
        <%= " (Current)" if sesh.session_token == session[:session_token]%>
      <%= button_to "logout", session_url(sesh), method: :delete%>
    <% end %>
  </ul>
</p>

<p>
  <%= link_to("Rent a cat!", new_cat_rental_request_url)%>
</p>

<%= link_to("See all approved requests", cat_rental_requests_url)%>

<p>
<%= link_to("Create a cat", new_cat_url)%>
</p>