config/routes.rb
Cats99::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :cats
  resources :cat_rental_requests do
    patch :approve
    patch :deny
  end
  root :to => 'cats#index'
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  VALID_COLORS = %w(black gray calico cream white orange vibrantpurple)

  validates :age, :birth_date, :color, :name, :sex, :user_id, :presence => true
  validates :sex, :inclusion => { in: ['M', 'F']}
  validates :color, :inclusion => { in: VALID_COLORS }
  validates :age, :numericality => true

  has_many :cat_rental_requests, :dependent => :destroy
  has_one :owner
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :require_login, only: [:new, :edit, :destroy, :update, :create]
  before_action :verify_cat_ownership, only: [:edit, :update, :destroy]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    @user = User.find(@cat.user_id)
    @requests = CatRentalRequest.where(:cat_id => @cat.id)
      .where("status = 'PENDING' OR status = 'APPROVED'")
      .order(:start_date)
    render :show
  end

  def edit
    @cat = Cat.find(params[:id])
    @colors = Cat::VALID_COLORS
    render :edit
  end

  def new
    @cat = Cat.new
    @colors = Cat::VALID_COLORS
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    @colors = Cat::VALID_COLORS
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    if @cat
      @cat.destroy
    else
      flash[:errors] = "No cat with that id"
    end
    redirect_to cats_url
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update_attributes(cat_params)
    @colors = Cat::VALID_COLORS
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:age, :name, :color, :sex, :birth_date)
  end

end

app/helpers/cats_helper.rb
module CatsHelper
  def verify_cat_ownership
    redirect_to cats_url unless cat_owner?
  end

  def cat_owner?
    Cat.find(params[:id]).user_id == current_user.id
  end


end

app/views/cats/_form.html.erb
<form action="<%= @cat.persisted? ? cat_url(@cat) : cats_url%>"
  method="POST" accept-charset="utf-8">
  <%== '<input type="hidden" name="_method" value="PATCH"/>' if @cat.persisted? %>

  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <p>
  <label_for="name">Name</label>
  <input type="text" name="cat[name]" id = "name" value = "<%= @cat.name %>" required/>
  </p>

  <p>
  <label_for="age">Age</label>
  <input type="text" name="cat[age]" id = "age" value = "<%= @cat.age %>" required/>
  </p>

  <p>
  <% ["M", "F"].each do |sex| %>
    <label_for="cat_sex_<%=sex%>"><%=sex%></label>
    <input type="radio" name="cat[sex]" id = "cat_sex_<%=sex%>" value = "<%=sex%>"
      <%== @cat.sex == sex ? "checked" : "" %> required />
  <% end %>
  </p>

  <p>
  <label_for="color">Coat Color</label>
  <select name="cat[color]" id = "color" required >
    <option></option>
    <% @colors.each do |color| %>
      <option value="<%=color%>" <%= @cat.color == color ? "selected": "" %>
         ><%=color%></option>
    <% end %>
  </select>
  </p>

  <p>
  <label_for="birth_date">Birth Date</label>
  <input type="date" name="cat[birth_date]" id = "birth_date"
    value = "<%= @cat.birth_date %>" required/>
  </p>

  <input type="submit"/>
</form>

app/views/cats/edit.html.erb
<h1>"Modify Your Cat!"</h1>

<%= render 'form' %>

app/views/cats/index.html.erb
<h1>Cats</h1>

<ul>
  <% @cats.each do |cat| %>
    <li> <%= link_to(cat.name, cat_url(cat)) %>
  <% end %>
</ul>


<p>
  <%= link_to("Rent a cat!", new_cat_rental_request_url)%>
</p>

<%= link_to("See all approved requests", cat_rental_requests_url)%>

<p>
<%= link_to("Create a cat", new_cat_url)%>
</p>

app/views/cats/new.html.erb
<h1>Create Your Cat!</h1>

<%= render 'form' %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Name</th>
    <td><%= @cat.name %></td>
  </tr>
  <tr>
    <th>Age</th>
    <td><%= @cat.age %></td>
  </tr>
  <tr>
    <th>Birthdate</th>
    <td><%= @cat.birth_date %></td>
  </tr>
  <tr>
    <th>Color</th>
    <td><%= @cat.color %></td>
  </tr>
  <tr>
    <th>Sex</th>
    <td><%= @cat.sex %></td>
  </tr>
</table>

<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Edit</th>
    <th>Delete</th>
    <th>Approve</th>
    <th>Deny</th>
  </tr>
  <%@requests.each do |request|%>
    <tr>
      <td><%= request.start_date%></td>
      <td><%= request.end_date%></td>
      <td><%= link_to("Edit", edit_cat_rental_request_url(request)) %></td>
      <td><%= button_to("Delete", cat_rental_request_url(request), method: :delete)%></td>
      <%if request.status == "PENDING" && cat_owner?%>
        <td><%= button_to("Approve", cat_rental_request_approve_url(request), method: :patch)%></td>
        <td><%= button_to("Deny", cat_rental_request_deny_url(request), method: :patch)%></td>
      <%elsif request.status == "APPROVED"%>
        <td>Approved!</td>
      <% end %>
    </tr>
  <% end %>
</table>

<p><%= link_to("Rent this cat!", new_cat_rental_request_url)%></p>

<p><%= link_to("Edit", edit_cat_url) %>
<%= button_to("Delete", cat_url, method: :delete)%></p>